# Generated by Django 5.2 on 2025-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('en-route', 'En Route'), ('pickup', 'Pickup'), ('in-progress', 'In Progress'), ('dropoff', 'Dropoff'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='requested', max_length=20),
        ),
    ]
