services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      target: development
    command: python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - backend
